config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
   :registrations => 'users/registrations',
   :sessions => 'users/sessions'
 }
  root to: 'items#index'
  resources :carts, only: [:index, :create, :update, :destroy]
  resources :orders, only: [:index, :create]
  # get '' => 'items#index', as: :items
  get '/item/:id' => 'items#show', as: :item
  get '/myPage' => 'users#show', as: :user
  #get '/basket' => 'carts#index', as: :basket
  #get '/purchase_history' => 'orders#index', as: :purchase_histroy
  match 'search' => 'items#search', via: [:get, :post], as: :search_items
  #resources :items, only: :show do
   # collection do
   #   match 'search' => 'item#search', via: [:get, :post], as: :search
   # end
  #end
end

app/models/cart.rb
class Cart < ApplicationRecord
	belongs_to :user
	belongs_to :item

	validates :user_id, presence: true
	validates :item_id, presence: true
	validates :quantity, presence: true, numericality: { greater_than: 0 }
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

	def index
		#'注文詳細を入力するための空のフォームを表示'
		@order = Order.new
		@carts = current_user.carts.includes(:item, item: :artist)
	end

	def create
		#'送信された情報を元にカートの項目を一つ作成'
		cart = Cart.new(cart_params)
		#'カートのDBが持ちたいユーザーIDを送信データに加える'
		cart.user_id = current_user.id
		#ユーザーIDと商品IDが一致するレコードを取得
		current_cart = current_user.carts.find_by(item_id: cart.item_id)
		#current_cartに何かしらの値が入ったか
		if current_cart.present?
			#存在しているなら、quantityを追加する
			current_cart.quantity += cart.quantity
			#在庫数チェック
			if current_cart.quantity > current_cart.item.stock
				redirect_to item_path(current_cart.item), alert: 'Please pick items fewer than our stock'
			else
				#セーブ&リダイレクト
				current_cart.save
				redirect_to carts_path
			end
		#'数量がなら'
		elsif cart.quantity <= 0
			#'itemのindexにリダイレクト'
			redirect_to item_path(cart.item), alert: 'The quantity must be greater than 0'
		#商品の個数が在庫より多い場合
		elsif cart.quantity > cart.item.stock
			reirect_to item_path(cart.item), alert: 'Please pick items fewer than our stock'
		else
			#'カート一件のデータを保存'
			cart.save
			#'カートのindexにリダイレクト'
			redirect_to carts_path
		end
	end

	def update
		#'編集したいカートのデータを取得'
		@cart = Cart.find(params[:id])
		current_quantity = @cart.quantity
		@cart.update(cart_params)
		if @cart.quantity <= 0
			@cart.destroy
			redirect_to carts_path
		elsif @cart.quantity > @cart.item.stock
			@cart.quantity = current_quantity
			@cart.save
			redirect_to carts_path, alert: 'Please pick items fewer than our stock'
		else
			redirect_to carts_path
		end
		# #'商品の個数が0なら'
		# if @cart.quantity <= 0
		# 	@cart.destroy
		# 	redirect_to carts_path
		# #在庫より注文数が多い場合
		# elsif @cart.quantity > @cart.item.stock
		# 	redirect_to carts_path, alert: 'Please pick items fewer than our stock'
		# else
		# 	#'送信された情報を元にカートのデータを更新'
		# 	@cart.update(cart_params)
		# 	redirect_to carts_path
		# end
	end

	def destroy
		#'削除したいカートのデータを取得'
		@cart = Cart.find(params[:id])
		#'カートのデータ一件を削除'
		@cart.destroy
		#'ページを更新'
		redirect_to carts_path
	end

	private
		def cart_params
			params.require(:cart).permit(:user_id, :item_id, :quantity)
		end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/index.html.erb
		<div class="container">

			<!-- タイトル -->
			<div class="row">
				<div class="col-md-12">
					<h2><b>Cart</b></h2>
				</div>
			</div><!-- end タイトル　-->

			<div class="row">
				<!-- 購入内容 -->
				<div class="col-md-12">

					<!-- 購入内容 -->
					<div class="row">
						<!-- 外枠　-->
						<div class="pre-scrollable" style="max-height: 500px;">
							<div class="col-md-12" style="border: 1px solid #ddd; border-radius: 4px;">

								<!-- CD内容　-->
								<% @carts.each do |cart| %>
									<div class="row" style= "margin: 15px auto;">
										<div class="col-md-3 ">
											<%= link_to item_path(cart.item) do %>
												<%= attachment_image_tag cart.item, :jacket_image, :fill, 130, 130, fallback: "no_img_130.png" %>
											<% end %>
										</div>
										<div class="col-md-7">
											<p><%= link_to cart.item.item_name, item_path(cart.item) %></p>
											<p><%= cart.item.artist.artist_name %></p>
											<p><%= number_to_currency(cart.item.price, :unit => "￥", :precision => 0) %></p>
											<div class="row">
												<div class="col-md-12 form-inline ">
													<%= form_for(cart) do |f| %>
														<%= f.select :quantity, (0..cart.item.stock).map{|i| [i, i]} %>
														<%= f.submit "update", class: "btn btn-default btn-sm"%>
														<%= link_to "delete", cart_path(cart), method: :delete, class: "btn btn-danger btn-sm" %>
													<% end %>
												</div><!-- end selectBox -->
											</div>
										</div>
										<div class="col-md-2" style= "margin-top: 40px;">
											<h4><b><%= number_to_currency(cart.item.price * cart.quantity, :unit => "￥", :precision => 0) %></b></h4>
										</div>
									</div><!-- end CD内容　-->
								<% end %>
							</div>
						</div><!-- end 外枠　-->
					</div><!-- end CD内容 -->

					<!-- 購入日・小計 -->

					<div class="row" style= "margin: 20px auto 0;">

						<div class="col-md-8"></div>
						<div class="col-md-2">
							<h3><b><%= number_to_currency(sub_total_each_carts, :unit => "￥", :precision => 0) %></b></h3>
						</div>
						<div class="col-md-2">
							<%= form_for(@order) do |f| %>
								<%= f.submit "Buy now", class: "btn btn-primary", style: "margin-top: 15px;", data: { confirm: "Total payment is #{sub_total_each_carts} yen, are you sure?" } %>
							</div>

						</div>

						<div class="row">
							<div class="col-md-12">
								<h2><b>Destination</b></h2>
							</div>
						</div>

						<div class="row">
							<div class="col-md-12" style="border: 1px solid #ddd; border-radius: 4px;">

								<div class="row" >
									<div class="col-md-12" style= "margin-top: 15px;">
										<label>First Name ※</label>
										<%= f.text_field :firstname, class: "form-control", value: current_user.firstname %>
									</div>
								</div>

								<div class="row" style= "padding-bottom: 15px;">
									<div class="col-md-12" style= "margin-top: 15px;">
										<label>Last Name ※</label>
										<%= f.text_field :lastname, class: "form-control", value: current_user.lastname %>
									</div>
								</div>

								<div class="row" style= "padding-bottom: 15px;">
									<div class="col-md-12">
										<label>Zip Code ※</label>
										<%= f.text_field :zip_code, class: "form-control", value: current_user.zip_code, placeholder: "XXXXXXX" %>
									</div>
								</div>

								<div class="row" style= "padding-bottom: 15px;">
									<div class="col-md-12">
										<label>Address ※</label>
										<%= f.text_field :address, class: "form-control", value: current_user.address, placeholder: "東京都 XXXXX XXXXX XXXXX XXXXX" %>
									</div>
								</div>

								<div class="row" style= "padding-bottom: 30px;">
									<div class="col-md-12">
										<label>Phone Number ※</label>
										<%= f.text_field :phone, class: "form-control", value: current_user.phone, placeholder: "XXXXXXXXXXX" %>
									</div>
								</div>
								<% end %>
							</div><!-- end 購入日・小計　-->
						</div>

					</div><!-- end 購入内容 -->

			</div><!-- end row-->



		</div><!-- end container-->