config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
   :registrations => 'users/registrations',
   :sessions => 'users/sessions'
 }
  root to: 'items#index'
  resources :carts, only: [:index, :create, :update, :destroy]
  resources :orders, only: [:index, :create]
  # get '' => 'items#index', as: :items
  get '/item/:id' => 'items#show', as: :item
  get '/myPage' => 'users#show', as: :user
  #get '/basket' => 'carts#index', as: :basket
  #get '/purchase_history' => 'orders#index', as: :purchase_histroy
  match 'search' => 'items#search', via: [:get, :post], as: :search_items
  #resources :items, only: :show do
   # collection do
   #   match 'search' => 'item#search', via: [:get, :post], as: :search
   # end
  #end
end

app/models/item.rb
class Item < ApplicationRecord
	belongs_to :admin
	belongs_to :artist
	belongs_to :genre

	attachment :jacket_image

	has_many :disks, dependent: :destroy
	has_many :songs, through: :disks
	has_many :item_orders
	has_many :carts
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	skip_before_action :authenticate_user!

	def index
		#'全ての商品のデータを取得'
		@items = Item.order(:updated_at).includes(:artist).page(params[:page]).reverse_order
		@q = Item.ransack(params[:q])
	end

	def show
		#'URLで指定されたITEM IDを持つデータを取得'
		@item = Item.find(params[:id])
		#'上の子であるディスクのデータを全て取得'
		@disks = @item.disks
		#Viewでは@disks each do |disk|、songs = disk.songs、songs each do |song|
		@cart = Cart.new
	end

	def search
		#Itemsコントローラーの範囲内での検索機能は、ransackのAdvanced Modeを使ってください
		@q = Item.ransack(params[:q])
		#37.2ms
		# results = @q.result.includes(artist, :songs).to_a.uniq
		# @items = Kaminari.paginate_array(results).page(params[:page])
		#10ms
		@items = @q.result(distinct: true).includes(:artist).joins(:artist, :songs).page(params[:page])
		#10ms
		# @items = @q.result(distinct: true).select('items.*').page(params[:page])

		render :index
		#indexページにおいて、@itemsはItemを全件取得しますが、searchメソッドをindexから実行した場合
		#@itemsで参照する値を検索結果に置き換えて、indexページを更新させます
	end

	private
		def item_params
			params.require(:item).permit(:item_name, :label, :jacket_image_id, :genre_id, :artist_id, :price, :stock, :admin_id, :delete_flag)
		end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/index.html.erb
				<div class="container">

					<!-- メインビジュアル -->
					<div class="row">
						<div class="top-message col-md-12" style="text-align:center">
							<h1  style="margin: 20px auto;">lyrical <strong>MMK</stong></h1>
							</div><!-- end メインビジュアル-->
						</div>

						<div class="row">
							<!-- 任意のID指定。クラスとデータ属性の指定。 -->
							<div id="carousel-example" class="carousel slide " data-ride="carousel" data-interval="5000">
								<!-- インジケーターの設置。下部の○●ボタン。 -->
								<ol class="carousel-indicators">
									<li data-target="#carousel-example" data-slide-to="0" class="active"></li>
									<li data-target="#carousel-example" data-slide-to="1"></li>
									<li data-target="#carousel-example" data-slide-to="2"></li>
									<li data-target="#carousel-example" data-slide-to="3"></li>
								</ol>

								<!-- スライドの内容 -->
								<div class="carousel-inner">
									<div class="item active">
										<%= image_tag "miura950x280.jpg", :width=>'100%' %>
									</div>
									<div class="item">
										<%= image_tag "amuro950x280.jpg", :width=>'100%' %>
									</div>
									<div class="item">
										<%= image_tag "hoshino950x280.jpg", :width=>'100%' %>
									</div>
									<div class="item">
										<%= image_tag "sym950x280.jpg", :width=>'100%' %>
									</div>
								</div>

								<!-- 左右の移動ボタン -->
								<a class="left carousel-control" href="#carousel-example" data-slide="prev">
									<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
								</a>
								<a class="right carousel-control" href="#carousel-example" data-slide="next">
									<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
								</a>
							</div>
						</div>



						<!-- CD陳列棚 -->
						<div class="row">
							<div class="col-md-12" style="background-color: black;">
								<!-- 検索フォーム -->
								<div class="row">
									<div class="col-md-1" style="line-height: 34px;margin: 15px 0;text-align:right;font-size: 20px;color: white;">
										<span> index</span>
									</div>

									<div class="input-group col-md-11" style="padding-right: 15px; margin: 15px auto;">
										<%= search_form_for @q, url: search_items_path, html: { method: :post } do |f| %>
											<%= f.search_field :item_name_or_artist_artist_name_or_songs_song_name_cont, style: "max-width: 1018px;", class: "form-control", placeholder: "Search" %>
											<span class="input-group-btn">
												<%= f.button :type => "submit", :class =>"btn btn-danger" do %>
													<span class="glyphicon glyphicon-search"></span>
												<% end %>
											</span>
										<% end %>
									</div>


									<!-- CDの陳列-->
									<% @items.each do |item| %>
									<div class="col-md-3">
										<div class="thumbnail" style="text-align:center;padding-top:10px;">
											<%=link_to item_path(item) do %>
											<% if item.stock > 0 %>
											<%= attachment_image_tag item, :jacket_image, :fill, 300, 300, fallback: "no_image.jpg", class: "img-circle" %>
											<% else %>
											<%= attachment_image_tag item, :jacket_image, :fill, 300, 300, fallback: "no_image.jpg", class: "img-circle", style: "filter: grayscale(100%);" %>
											<% end %>
											<% end %>

											<div class="caption">
												<p><b><%= item.item_name %></b></p>
												<p><%= item.artist.artist_name %></p>
												<% if item.stock <= 0 %>
												<p style="color: red;">Out of stock</p>
												<% else %>
												<p><%= number_to_currency(item.price, :unit => "￥", :precision => 0) %></p>
												<% end %>
											</div>
										</div>
									</div>
									<% end %>
									<!-- CD陳列ここまで -->


									<div class="col-md-12" style="text-align: center;">
										<%= paginate @items %>
									</div>
								</div>
							</div>


						</div><!-- end CD陳列棚-->



					</div><!-- end container-->

app/views/items/show.html.erb
		<div class="container">

			<!-- タイトル -->
			<div class="row">
				<div class="col-md-12">
					<h2><b><%= @item.item_name %></b></h2>
				</div>
			</div><!-- end タイトル　-->

			<div class="row">
				<!-- CD紹介 -->
				<div class="col-md-7">
					<!-- CD内容 -->
					<div>
						<p><b><%= @item.genre.genre_name %></b></p>
						<p><b><%= @item.artist.artist_name %></b></p>
						<p><b><%= @item.label %></b></p>
						<p><b><%= number_to_currency(@item.price, :unit => "￥", :precision => 0) %>&nbsp;&nbsp;&nbsp;/&nbsp;&nbsp;
						<% if @item.stock > 0 %><span style="color: green;">In stock</span><% else %><span style="color: red;">Out of stock</span><% end %></b></p>
					</div><!-- end CD内容-->
					<br>
					<!-- 収録曲 -->
					<div class="row">
						<div  class="pre-scrollable" style="max-height: 500px";>
							<% @disks.order(:disk_number).each do |disk| %>
								<div class="col-md-12" style="margin-top: 10px;">
									<p><b>Disk.<%= disk.disk_number %></b></p>
								</div>
								<% disk.songs.includes(:artist).order(:track_number).each do |song| %>
									<div class="col-md-6">
										<p>&nbsp;&nbsp;<%= song.track_number %>.<%= song.song_name %></p>
									</div>
									<div class="col-md-4" style="background-color: white;">
										<p>&nbsp;<%= song.artist.artist_name %></p>
									</div>
									<div class="col-md-2">
										<p><%= calc_minute(song) %>:<%= song.song_length.strftime("%S") %></p>
									</div>
								<% end %>
							<% end %>
						</div>
					</div><!-- end 収録曲-->


				</div><!-- end CD紹介 -->

				<!-- ジャケット部分 -->
				<div class="col-md-5">
					<div style="text-align:center";>
						<% if @item.stock > 0 %>
							<%= attachment_image_tag @item, :jacket_image, :fill, 300, 300, fallback: "no_img.png" %>
						<% else %>
							<%= attachment_image_tag @item, :jacket_image, :fill, 300, 300, fallback: "no_img.png", style: "filter: grayscale(100%);"  %>
						<% end %>
					</div>
					<br>
					<%= form_for(@cart) do |f| %>
						<div class="row">
							<div class="col-md-4"></div><!-- selectBox調整col -->
							<!-- selectBox -->
							<div class="col-md-2 input-lg">
								<%= f.select :quantity, (1..@item.stock).map{|i| [i, i]} %>
								<%= f.hidden_field :item_id, value: @item.id, readonly: true %>
							</div><!-- end selectBox -->

							<!-- cartボタン -->
							<div class="col-md-6" style="padding-top: 5px;">
								<% if @item.stock > 0 %>
									<%= f.submit "Add to cart", class: "btn btn-success" %>
								<% end %>
							</div>
						</div>
					<% end %>
				</div><!-- end ジャケット部分 -->

			</div><!-- end row-->



		</div><!-- end container-->