config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
   :registrations => 'users/registrations',
   :sessions => 'users/sessions'
 }
  root to: 'items#index'
  resources :carts, only: [:index, :create, :update, :destroy]
  resources :orders, only: [:index, :create]
  # get '' => 'items#index', as: :items
  get '/item/:id' => 'items#show', as: :item
  get '/myPage' => 'users#show', as: :user
  #get '/basket' => 'carts#index', as: :basket
  #get '/purchase_history' => 'orders#index', as: :purchase_histroy
  match 'search' => 'items#search', via: [:get, :post], as: :search_items
  #resources :items, only: :show do
   # collection do
   #   match 'search' => 'item#search', via: [:get, :post], as: :search
   # end
  #end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Lyricalmmk</title>
	<%= csrf_meta_tags %>

	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
	<header class="navbar navbar-fixed-top navbar-inverse">
		<div class="container">
			<nav class="nav2 navbar-nav navbar-left">
				<span class="glyphicon glyphicon-heart-empty">MMK</span>
			</nav>
			<nav>
				<ul class="nav navbar-nav navbar-right">
					<% if user_signed_in? %>
						<li><%=link_to "#{current_user.firstname}, Welcome!", orders_path, class: "glyphicon", :style=>"font-weight:bold;" %></li>
						<li><%=link_to ' CD', root_path, class: "glyphicon glyphicon-cd" %></li>
						<li><%=link_to ' MyPage', user_path, class: "glyphicon glyphicon-user" %></li>
						<li><%=link_to ' Cart', carts_path, class: "glyphicon glyphicon-shopping-cart" %></li>
						<li><%= link_to " logout", destroy_user_session_path, class: "glyphicon glyphicon-log-out", method: :delete %></li>
					<% else %>
						<li><%=link_to " CD", root_path, class: "glyphicon glyphicon-cd" %></li>
						<li><%= link_to " signup", new_user_registration_path, class: "glyphicon glyphicon-edit"%></li>
						<li><%= link_to " login", new_user_session_path, class: "glyphicon glyphicon-log-in"%></li>
					<% end %>
				</ul>
			</nav>
		</div>
	</header>
	<% flash.each do |key, value| %>
        <h3 class="alert alert-<%= key %>"><%= value %></h3>
    <% end %>

	<%= yield %>

	<footer>
		<div class="container">
			<div class="row">
				<div class="col-xs-3 col-xs-offset-10">
					<p>CopyRight &copy;lyrical MMK</p>
				</div>
			</div>
		</div>
	</footer>
</body>


</html>